sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - 4
  - 5
  - 6
before_install:
  - gem update --system
  - gem install scss-lint
  - npm i -g npm
before_script:
  - npm prune